SPOTIFY= [
  ["君はともだち（Orgel ver.）", 77.997, "https://open.spotify.com/track/1mRmHeJqKoAeSlEK4JAwHK"],
  ["いつか夢で（Orgel ver.）", 77.931, "https://open.spotify.com/track/3vjTqcDXUINnVIFC3kGiQK"],
  ["イッツ・ア・スモール・ワールド（Orgel ver.）", 75.874, "https://open.spotify.com/track/1YrMVbCeXu4lKVsbQW18Hq"],
  ["ララルー（Orgel ver.）", 76.002, "https://open.spotify.com/track/25zAsDFEXzp7M92TrI3SeW"],
  ["君はともだち - Orgel ver.", 78.029, "https://open.spotify.com/track/2TJR3xMojSXKoIoykbsMjf"],
  ["いつか夢で - Orgel ver.", 77.926, "https://open.spotify.com/track/6F714Rnn5z2XlmPi9lW7Q6"],
  ["くまのプーさん [『くまのプーさん』より] - Music Box Lullaby Ver.", 72.015, "https://open.spotify.com/track/0bvF12LnLi8JCiYv1XymxK"],
  ["君はともだち(映画「トイストーリー」より)[Music Box]", 75.999, "https://open.spotify.com/track/1ZUbNwf4IKvX4J5120QMdX"],
  ["レット・イット・ゴー〜ありのままで〜(映画「アナと雪の女王」より)[Music Box]", 75.002, "https://open.spotify.com/track/2jqvkk2EKxicbdCs7qgoZI"],
  ["いつか王子様が(映画「白雪姫」より)[Music Box]", 74.971, "https://open.spotify.com/track/6ZpJ1kp5JzFDnmJbRmjbAf"],
["星に願いを/ピノキオ (Music Box)", 79.965, "https://open.spotify.com/track/5VIFtCDcEcvBseWZ2VIhQt"], 
["いつも何度でも", 78.042, "https://open.spotify.com/track/61EKfBRl5PkjXtEb4rVwDX"], 
["カントリー・ロード", 76.015, "https://open.spotify.com/track/31gjHFVW3FgrqkXcDlnfIf"], 
["シータの決意 (天空の城ラピュタ) ~オルゴールバージョン~", 75.0, "https://open.spotify.com/track/4JagYaSVkt1NaB9SCEQ0dg"],
 ["さんぽ(となりのトトロより) - (Orgel ver.)", 79.98, "https://open.spotify.com/track/49qmkkLyTac0Y8LCpJSqyC"],
 ["さよならの夏(コクリコ坂より) - (Orgel ver.)", 79.943, "https://open.spotify.com/track/2mLNOrulmhbbaIyZhDzwqi"],
 ["もののけ姫 - もののけ姫より", 79.823, "https://open.spotify.com/track/1o3vdz977aljFfokOgRU2p"],
 ["Wherever you are (オルゴール・バージョン)", 75.008, "https://open.spotify.com/track/4FlgYYEBWDq3D1z4E3jTm1"], ["Pretender", 79.98, "https://open.spotify.com/track/3ZAgUgGlan7e9BkIXaULk3"],
 ["I LOVE...", 76.998, "https://open.spotify.com/track/4x7KvnrogKsGEnbp8OGvZv"],
["馬と鹿", 79.979, "https://open.spotify.com/track/26mk96CDijm3nPYEtTd3PF"],
 ["パプリカ", 75.987, "https://open.spotify.com/track/5gUH1DrHuTHfEnTQsci1WV"],
 ["The Beginning (Originally performed by ONE OK ROCK) - オルゴール", 76.491, "https://open.spotify.com/track/5Cx5DN8QCLpbDBD2jMU3cj"],
 ["カブトムシ (Originally performed by aiko)", 74.708, "https://open.spotify.com/track/6xF355cOPhg9h4Rxs3S0VQ"], 
["明日に架ける橋 （オルゴール）", 78.999, "https://open.spotify.com/track/4svMy7q0JLWOZGmkQhR12b"], 
["ヘイ・ジュード （オルゴール）", 77.989, "https://open.spotify.com/track/2EaL70geK2Q8Nbf3hrpMCx"], 
["Time After Time(懐かしの洋楽ポップスオルゴール)", 77.005, "https://open.spotify.com/track/466n9MMmHqjt3aDmirkGTH"], ["SAKURA(Originally Performed By いきものがかり)(Instrumental)", 74.019, "https://open.spotify.com/track/6oTVYKXTizNax4mWUQ1VaF"],
 ["旅立ちの日に", 72.829, "https://open.spotify.com/track/1PXDJN3V0es2GR4CGz6SdN"],
 ["言葉にできない/小田和正", 79.009, "https://open.spotify.com/track/1lZVZJU6PUEal2nKRs1uIj"],
["栄光の架橋 (ゆず)", 76.997, "https://open.spotify.com/track/68gb9YQg7p3q8RmzWwi82k"], 
["Soranji (映画「ラーゲリより愛を込めて」主題歌)(オリジナル:Mrs. GREEN APPLE)(アコースティック&エレクトリックピアノDUO)", 77.981, "https://open.spotify.com/track/2DnStbk7ddWaR0ROHYzucR"], 
["私は最強 - Piano Cover", 75.009, "https://open.spotify.com/track/7ev7g8o2psgX3pcWeWEPZc"],
 ["点描の唄 - Piano Cover", 70.027, "https://open.spotify.com/track/3KBjQpJPK615ZILkB8uIwk"], 
["CHEERS（オルゴール）", 79.997, "https://open.spotify.com/track/0SDKER8vLHprRyUmdhvhBH"], 
["リライト ～「鋼の錬金術師」より～（オルゴール）", 77.496, "https://open.spotify.com/track/6yjwuvPvthApzwhafk2AOg"], 
["逆夢 「劇場版 呪術廻戦 0」エンディングテーマ(オルゴール)", 77.981, "https://open.spotify.com/track/6Xgi6HS52L31nIyj1ejqzG"], ["Cry Baby ～アニメ「東京リベンジャーズ」オープニング主題歌～（オルゴール）", 79.982, "https://open.spotify.com/track/6sgjnQHcdvEYskUqpuxxTM"], 
["竈門炭治郎のうた - 椎名 豪 featuring 中川奈美 - アニメ『鬼滅の刃』より - オルゴール", 75.015, "https://open.spotify.com/track/1nMDjaAlig8uy2W8rx6ZGO"],
 ["花占い - (オルゴール) [Cover] - 『ボクの殺意が恋をした』より - Vaundy", 78.022, "https://open.spotify.com/track/4h22qow5pp4IAFVWrEaOss"],
["怪獣の花唄 - オルゴール - Cover - Vaundy", 78.005, "https://open.spotify.com/track/7eNzZYvoQrCN6Zt3WG2OL9"], ["Shout Baby ~アニメ「僕のヒーローアカデミア」エンディングテーマ~ (オルゴール)", 75.012, "https://open.spotify.com/track/2LshbV1eWfDcJpD9YOwnRd"],
 ["キミがいれば『名探偵コナン』より(2022 Remastered Version)", 75.011, "https://open.spotify.com/track/0UTxa1KPj8Ic2mhCnqZfPl"],
 ["十九の春", 69.964, "https://open.spotify.com/track/5ZsOf6L5LPZqMMgqDZUO04"], 
["Spring Day (Piano Solo)", 67.478, "https://open.spotify.com/track/1gJ2W96QFxHxrHVShwwivC"], 
["Euphoria", 70.003, "https://open.spotify.com/track/76lZGNivdvaevBxiALgx32"], 
["G線上のアリア", 77.009, "https://open.spotify.com/track/2va7KHKyTtqnUUWP08UABn"],
 ["ピアノ協奏曲", 74.99, "https://open.spotify.com/track/6mmusRhvkNOqecWHEsWbAe"],
 ["メヌエット ト長調", 75.006, "https://open.spotify.com/track/73dHni3FIZPDBXDbLdqHmx"], 
["亜麻色の髪の乙女", 79.982, "https://open.spotify.com/track/7jMFmT2oJ3c6GxRNcwnx3c"],
["ジョルダーニ:カロ・ミオ・ベン(いとしい女よ) (オルゴール)", 77.004, "https://open.spotify.com/track/285sDqmvAZyOUSbIjkwTHS"], 
["Zero O' Clock", 76.175, "https://open.spotify.com/track/52gNckuUZCEpWwFl8n9Som"], 
["Best of Me", 69.484, "https://open.spotify.com/track/0zDTpAgIFji5a5ijHJtkX0"], 
["Intro: Singularity", 73.61, "https://open.spotify.com/track/4UqzyL6YQQY2bmghpTwvki"], 
["Euphoria", 70.003, "https://open.spotify.com/track/6EKT5Wo2izVKgZxff4R3nT"],
 ["Magic Shop", 70.13, "https://open.spotify.com/track/0V8q89O46QJ8OLvH5wkZ6M"], 
["Friends", 76.732, "https://open.spotify.com/track/1PgW4zrkIPHT3s1E5lV7rw"],
 ["Brahms Lullaby", 73.988, "https://open.spotify.com/track/64MhdTI2NpxFmxT4Iy4Zxr"], 
["A Little Boat", 73.202, "https://open.spotify.com/track/6ahZWO4bnowdtkAJwkahWD"],
["daisy", 76.004, "https://open.spotify.com/track/4Wpot9tmOGZ5OQ1HNNeo3x"], 
["Willow Song", 75.924, "https://open.spotify.com/track/4U7P98xdvMWtAkhP6M0Kj7"],
 ["Babblarnas vaggvisa", 73.467, "https://open.spotify.com/track/4sw1BjunB4P1rCTPanYKZV"],
 ["Grandpa's Story", 73.518, "https://open.spotify.com/track/3QqrJEPHBoaONZFNNbcQ8s"],
 ["Baby Bear", 68.257, "https://open.spotify.com/track/5UpHz8cxbWTNIwu0zbxSqk"], 
["Goodnight", 77.82, "https://open.spotify.com/track/4514yczhgbgkqFCa3ymD8p"], 
["Teddys Dream", 76.872, "https://open.spotify.com/track/4yAXm981wdQVYAynH6zMZD"],
 ["One Two Three", 70.605, "https://open.spotify.com/track/6xzTftimykDDWxCKVzICLC"], 
["My Beautiful Angel", 72.225, "https://open.spotify.com/track/6Qn9XmS9eJuCUiSe18BDTO"],
 ["Doux rêves", 77.39, "https://open.spotify.com/track/3v0QpPVFnMZAScYmxxwcLg"], 
["Little Cat", 72.9, "https://open.spotify.com/track/6dHzijXrFnRCsCzPyiwLPJ"],
 ["Stars Cuddling", 72.056, "https://open.spotify.com/track/46VaVaE0Ik3QhyJX36ZIGs"], 
["Yankee Doodle", 73.801, "https://open.spotify.com/track/1rPArr7MqVeVEWlbCKIotc"], 
["Ida's Summer Song", 74.98, "https://open.spotify.com/track/1SqsTpz4vrbP0iA5qDn0W5"], 
["Dreamscape", 77.999, "https://open.spotify.com/track/3xr80E2YijvMBXXZVk3Xds"],
 ["In My Boat", 80.34, "https://open.spotify.com/track/0mC9TvIZIbKv13zKhRl2Rk"],
 ["Bedtime story", 74.822, "https://open.spotify.com/track/1pZ50uCdpTPoiZHgA0dTdy"], 
["Thinking of you (西野カナ)", 75.99, "https://open.spotify.com/track/58INaVJwSKXb1MsG0l5HES"],
["beloved (西野カナ)", 74.991, "https://open.spotify.com/track/2Mp3jUiHarbSHoHHQMKCa2"],
 ["あなたの 好きな ところ (オルゴール)", 75.268, "https://open.spotify.com/track/1qGZhZd2XcdiFjIyNNFKMn"], 
["へでもねーよ - (オルゴール) [Cover] - 藤井風", 76.989, "https://open.spotify.com/track/1NxpMOw84LfW2TNJAzH7c7"], 
["死ぬのがいいわ - オルゴール - Cover - 藤井風", 78.015, "https://open.spotify.com/track/6gdb8h3qePWCdQ3Dnln1q2"],
 ["夢じゃない", 76.987, "https://open.spotify.com/track/476DtCbXxgVlzB3i58CwUf"],
 ["花束を君に Originally Performed By 宇多田ヒカル (オルゴール)", 76.457, "https://open.spotify.com/track/6kDDSYX5mq4I2HXjcaVt3N"],
 ["I CAN'T STOP ME - オルゴールカバー", 74.978, "https://open.spotify.com/track/63WDwj44LhVWrhmaCWg8U0"], 
["亡き王女の為のセプテット+U.N.オーエンは彼女なのか?(東方紅魔郷)PIANO", 68.33, "https://open.spotify.com/track/1v1wgC1cx1UVLGKRVo0btr"],
["紅魔館に鳴り響くピアノ -フラワリングナイト", 70.397, "https://open.spotify.com/track/1t0mdEDaz4ZTdDTbOMw5dh"], 
["ゴーストリード(東方神霊廟)PIANO", 74.984, "https://open.spotify.com/track/1tPwNno4TKIhpwxnLJEmO6"], 
["ネイティブフェイス EXTRAボス・洩矢 諏訪子(東方風神録)+砕月(東方萃夢想)PIANO", 74.991, "https://open.spotify.com/track/3r4oeZZ31fzyP3dYXPAaPT"], 
["ネクロファンタジア(東方妖々夢)Healing Piano", 69.96, "https://open.spotify.com/track/32Epe6EY1vJu5OaKW7Ygfp"], 
["ラクトガール(東方紅魔郷)Healing Piano", 68.008, "https://open.spotify.com/track/6V6UfM0Hn0sm54380GQNP8"], 
["東方萃夢想〜砕月(東方萃夢想~東方緋想天)Healing Piano", 69.15, "https://open.spotify.com/track/0yV9PsfaisZIbrnPw1O3na"], ["おてんば恋娘(東方紅魔郷)Healing Piano", 79.995, "https://open.spotify.com/track/0GWnmFprwcuC4HlWAfTT26"], 
["風神少女(東方花映塚)Healing Piano", 68.658, "https://open.spotify.com/track/24JNA8viLwrN5vYLpsNDnC"], 
["幻想子守唄のピアノワルツ 東方イメージ(東方Project)PIANO", 75.058, "https://open.spotify.com/track/2Y0aPh3cAeb6OJv0UKpM6P"],
 ["感情の摩天楼(東方星蓮船)Healing Piano", 71.489, "https://open.spotify.com/track/6UmIupS6fvncPtNdYUYNUq"], 
["東方ピアノ子守唄(CD150枚記念作品) MIX", 72.343, "https://open.spotify.com/track/0HfU7l3T1Yh30hUPpwRMvn"],
 ["十六夜咲夜 の 「フラワリングナイト〜紅魔メドレー」(東方花映塚・東方紅魔郷)", 71.523, "https://open.spotify.com/track/7GpEA47r8SnLuvoOYlFpG4"]
]
